/**
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.spectra;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binary Reg Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tau.smlab.syntech.spectra.BinaryRegExp#getOp <em>Op</em>}</li>
 *   <li>{@link tau.smlab.syntech.spectra.BinaryRegExp#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see tau.smlab.syntech.spectra.SpectraPackage#getBinaryRegExp()
 * @model
 * @generated
 */
public interface BinaryRegExp extends RegExp
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see tau.smlab.syntech.spectra.SpectraPackage#getBinaryRegExp_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link tau.smlab.syntech.spectra.BinaryRegExp#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(RegExp)
   * @see tau.smlab.syntech.spectra.SpectraPackage#getBinaryRegExp_Right()
   * @model containment="true"
   * @generated
   */
  RegExp getRight();

  /**
   * Sets the value of the '{@link tau.smlab.syntech.spectra.BinaryRegExp#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(RegExp value);

} // BinaryRegExp
