/**
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.spectra;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tau.smlab.syntech.spectra.BooleanTerm#getRelExpr <em>Rel Expr</em>}</li>
 * </ul>
 *
 * @see tau.smlab.syntech.spectra.SpectraPackage#getBooleanTerm()
 * @model
 * @generated
 */
public interface BooleanTerm extends EObject
{
  /**
   * Returns the value of the '<em><b>Rel Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel Expr</em>' containment reference.
   * @see #setRelExpr(TemporalExpression)
   * @see tau.smlab.syntech.spectra.SpectraPackage#getBooleanTerm_RelExpr()
   * @model containment="true"
   * @generated
   */
  TemporalExpression getRelExpr();

  /**
   * Sets the value of the '{@link tau.smlab.syntech.spectra.BooleanTerm#getRelExpr <em>Rel Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel Expr</em>' containment reference.
   * @see #getRelExpr()
   * @generated
   */
  void setRelExpr(TemporalExpression value);

} // BooleanTerm
