/**
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.spectra;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Param</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tau.smlab.syntech.spectra.SpectraPackage#getPatternParam()
 * @model
 * @generated
 */
public interface PatternParam extends Referrable
{
} // PatternParam
