/**
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.spectra;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Or Pattern Referrable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tau.smlab.syntech.spectra.SpectraPackage#getPredicateOrPatternReferrable()
 * @model
 * @generated
 */
public interface PredicateOrPatternReferrable extends EObject
{
} // PredicateOrPatternReferrable
