(define
  (problem Goal)
  (:domain DirectedController)
  (:init
    (at $0 $Machine-0)
    (at $0 $TU)
    (at $0 $Machine-2)
    (at $0 $Machine-1)
    (at $0 $Buffer-2)
    (at $0 $Buffer-3)
    (at $0 $Buffer-4)
    (at $0 $Buffer-1)
    (at $0 $Machine-3)
  )
  (:goal
    (and
      (status event)
      (hoop $Machine-0)
      (hoop $TU)
      (hoop $Machine-2)
      (hoop $Machine-1)
      (hoop $Buffer-2)
      (hoop $Buffer-3)
      (hoop $Buffer-4)
      (hoop $Buffer-1)
      (hoop $Machine-3)
    )
  )
)
