/**
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.spectra.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import tau.smlab.syntech.spectra.PredicateOrPatternReferrable;
import tau.smlab.syntech.spectra.SpectraPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Predicate Or Pattern Referrable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PredicateOrPatternReferrableImpl extends MinimalEObjectImpl.Container implements PredicateOrPatternReferrable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PredicateOrPatternReferrableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpectraPackage.Literals.PREDICATE_OR_PATTERN_REFERRABLE;
  }

} //PredicateOrPatternReferrableImpl
