/**
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.spectra.impl;

import org.eclipse.emf.ecore.EClass;

import tau.smlab.syntech.spectra.SpectraPackage;
import tau.smlab.syntech.spectra.TypeConstant;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TypeConstantImpl extends ReferrableImpl implements TypeConstant
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeConstantImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpectraPackage.Literals.TYPE_CONSTANT;
  }

} //TypeConstantImpl
