/*
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpectraScopeProvider extends DelegatingScopeProvider {
}
