/*
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tau.smlab.syntech.Spectra.ui.internal.SpectraActivator;

public class SpectraUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpectraActivator.getInstance().getInjector("tau.smlab.syntech.Spectra");
	}

}
