/*
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSpectraValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(tau.smlab.syntech.spectra.SpectraPackage.eINSTANCE);
		return result;
	}
}
