/*
 * generated by Xtext 2.25.0
 */
package tau.smlab.syntech.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tau.smlab.syntech.parser.antlr.internal.InternalSpectraParser;
import tau.smlab.syntech.services.SpectraGrammarAccess;

public class SpectraParser extends AbstractAntlrParser {

	@Inject
	private SpectraGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSpectraParser createParser(XtextTokenStream stream) {
		return new InternalSpectraParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SpectraGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SpectraGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
